//! The registry index — the catalogue the ✚ Browse tab reads.
//!
//! One JSON document, served over HTTP, listing packages and the versions each
//! one has published. JSON rather than RON because it is a *web* file: it is
//! generated by the site, cached by a CDN, and read by things that are not this
//! editor.
//!
//! ```json
//! { "packages": [ {
//!     "id": "com.example.grass", "name": "Grass Tools",
//!     "description": "…", "author": "Example", "keywords": ["terrain"],
//!     "versions": [ { "version": "1.2.0", "engine": ">=0.55.0",
//!                     "git": "https://github.com/example/grass.git", "rev": "v1.2.0" } ]
//! } ] }
//! ```
//!
//! Every published version says **where to get it**, so installing from the
//! catalogue is the Git path with the URL filled in — there is no second
//! download-and-unpack mechanism to get wrong, and a package listed here can be
//! installed by hand from the same URL by anybody who would rather not use the
//! browser.
//!
//! Fetching is the caller's job. This module parses, searches and sorts; it
//! opens no sockets, which is what makes it testable.

use serde::{Deserialize, Serialize};

use crate::version::{Version, VersionReq};

/// Where the catalogue lives. Overridable per install for a private registry.
pub const DEFAULT_INDEX_URL: &str = "https://fopull.com/packages/index.json";

/// One published version of a package.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Release {
    pub version: Version,
    /// Engine range, as in the manifest. Absent = any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub engine: Option<VersionReq>,
    /// The repository to clone.
    pub git: String,
    /// Branch, tag or commit. Absent = the default branch, which is a moving
    /// target — a published release should name one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rev: Option<String>,
    /// Folder inside the repository holding `package.ron`, when it is not the
    /// root.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subdir: Option<String>,
}

/// One package in the catalogue.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Listing {
    pub id: String,
    pub name: String,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub author: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub homepage: Option<String>,
    #[serde(default)]
    pub keywords: Vec<String>,
    #[serde(default)]
    pub versions: Vec<Release>,
}

impl Listing {
    /// The newest release this engine can actually run — which is not always
    /// the newest release. A catalogue row that offers a version the editor
    /// will refuse on install is a row that wastes somebody's afternoon.
    pub fn best_for(&self, engine: &Version) -> Option<&Release> {
        self.versions
            .iter()
            .filter(|r| r.engine.as_ref().is_none_or(|req| req.matches(engine)))
            .max_by(|a, b| a.version.cmp(&b.version))
    }

    /// The newest release, whatever engine it wants.
    pub fn newest(&self) -> Option<&Release> {
        self.versions.iter().max_by(|a, b| a.version.cmp(&b.version))
    }

    /// Does this row match a search box's contents? Case-insensitive over id,
    /// name, description and keywords, every whitespace-separated word having
    /// to match somewhere — so "grass terrain" finds a terrain package about
    /// grass and not every package about either.
    pub fn matches(&self, query: &str) -> bool {
        let q = query.trim().to_lowercase();
        if q.is_empty() {
            return true;
        }
        let hay = format!(
            "{} {} {} {}",
            self.id.to_lowercase(),
            self.name.to_lowercase(),
            self.description.to_lowercase(),
            self.keywords.join(" ").to_lowercase()
        );
        q.split_whitespace().all(|w| hay.contains(w))
    }
}

/// The whole catalogue.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct Index {
    #[serde(default)]
    pub packages: Vec<Listing>,
}

impl Index {
    pub fn parse(json: &str) -> Result<Index, String> {
        serde_json::from_str(json).map_err(|e| format!("the package catalogue would not read: {e}"))
    }

    /// Rows matching `query`, best matches first: an id or name that starts
    /// with the query beats one that merely contains it, then alphabetical.
    pub fn search(&self, query: &str) -> Vec<&Listing> {
        let q = query.trim().to_lowercase();
        let mut hits: Vec<&Listing> = self.packages.iter().filter(|l| l.matches(&q)).collect();
        hits.sort_by_key(|l| {
            let rank = if q.is_empty() {
                1
            } else if l.name.to_lowercase().starts_with(&q) || l.id.to_lowercase().starts_with(&q) {
                0
            } else {
                1
            };
            (rank, l.name.to_lowercase())
        });
        hits
    }

    pub fn find(&self, id: &str) -> Option<&Listing> {
        self.packages.iter().find(|l| l.id == id)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = r#"{
        "packages": [
            { "id": "com.example.grass", "name": "Grass Tools",
              "description": "Scatter and paint grass on terrain",
              "author": "Example", "keywords": ["terrain", "vegetation"],
              "versions": [
                {"version": "1.0.0", "git": "https://x/g.git", "rev": "v1.0.0"},
                {"version": "2.0.0", "engine": ">=9.0.0", "git": "https://x/g.git", "rev": "v2.0.0"},
                {"version": "1.4.0", "engine": ">=0.55.0", "git": "https://x/g.git", "rev": "v1.4.0"}
              ] },
            { "id": "com.other.audio", "name": "Audio Kit",
              "description": "Reverb impulse responses", "author": "Other",
              "versions": [{"version": "0.3.0", "git": "https://x/a.git"}] }
        ]
    }"#;

    #[test]
    fn parses_the_catalogue() {
        let idx = Index::parse(SAMPLE).unwrap();
        assert_eq!(idx.packages.len(), 2);
        assert_eq!(idx.find("com.example.grass").unwrap().name, "Grass Tools");
    }

    /// The row must not offer a version this engine will refuse on install.
    #[test]
    fn the_offered_version_is_the_newest_this_engine_can_run() {
        let idx = Index::parse(SAMPLE).unwrap();
        let grass = idx.find("com.example.grass").unwrap();
        assert_eq!(grass.newest().unwrap().version, Version::new(2, 0, 0));
        let best = grass.best_for(&Version::new(0, 55, 0)).unwrap();
        assert_eq!(best.version, Version::new(1, 4, 0));
        assert_eq!(best.rev.as_deref(), Some("v1.4.0"));
    }

    #[test]
    fn a_release_with_no_engine_range_runs_anywhere() {
        let idx = Index::parse(SAMPLE).unwrap();
        let audio = idx.find("com.other.audio").unwrap();
        assert!(audio.best_for(&Version::new(0, 1, 0)).is_some());
    }

    #[test]
    fn search_needs_every_word_to_match() {
        let idx = Index::parse(SAMPLE).unwrap();
        assert_eq!(idx.search("grass").len(), 1);
        assert_eq!(idx.search("grass terrain").len(), 1);
        assert_eq!(idx.search("grass reverb").len(), 0);
        assert_eq!(idx.search("").len(), 2);
        // Keywords count, and so does the id.
        assert_eq!(idx.search("vegetation").len(), 1);
        assert_eq!(idx.search("com.other").len(), 1);
    }

    #[test]
    fn a_name_that_starts_with_the_query_sorts_first() {
        let idx = Index::parse(
            r#"{"packages":[
                {"id":"com.a.b","name":"Zebra grass","versions":[]},
                {"id":"com.c.d","name":"Grass Tools","versions":[]}
            ]}"#,
        )
        .unwrap();
        let hits = idx.search("grass");
        assert_eq!(hits[0].name, "Grass Tools");
    }

    #[test]
    fn a_malformed_catalogue_says_so_in_words() {
        let err = Index::parse("{ nope").unwrap_err();
        assert!(err.contains("catalogue"), "{err}");
    }

    #[test]
    fn round_trips() {
        let idx = Index::parse(SAMPLE).unwrap();
        let text = serde_json::to_string(&idx).unwrap();
        assert_eq!(Index::parse(&text).unwrap(), idx);
    }
}
