//! The registry index — the catalogue the ✚ Browse tab reads.
//!
//! One JSON document, served over HTTP, listing packages and the versions each
//! one has published. JSON rather than RON because it is a *web* file: it is
//! generated by the site, cached by a CDN, and read by things that are not this
//! editor.
//!
//! ```json
//! { "packages": [ {
//!     "id": "com.example.grass", "name": "Grass Tools",
//!     "description": "…", "author": "Example", "keywords": ["terrain"],
//!     "versions": [ { "version": "1.2.0", "engine": ">=0.55.0",
//!                     "git": "https://github.com/example/grass.git", "rev": "v1.2.0" } ]
//! } ] }
//! ```
//!
//! Every published version says **where to get it**, so installing from the
//! catalogue is the Git path with the URL filled in — there is no second
//! download-and-unpack mechanism to get wrong, and a package listed here can be
//! installed by hand from the same URL by anybody who would rather not use the
//! browser.
//!
//! Fetching is the caller's job. This module parses, searches and sorts; it
//! opens no sockets, which is what makes it testable.

use serde::{Deserialize, Deserializer, Serialize};

use crate::contents::Facet;
use crate::manifest::{Category, Media, Permission};
use crate::version::{Version, VersionReq};

/// Where the catalogue lives. Overridable per install for a private registry.
pub const DEFAULT_INDEX_URL: &str = "https://fopull.com/packages/index.json";

/// One published version of a package.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Release {
    pub version: Version,
    /// Engine range, as in the manifest. Absent = any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub engine: Option<VersionReq>,
    /// The repository to clone.
    pub git: String,
    /// Branch, tag or commit. Absent = the default branch, which is a moving
    /// target — a published release should name one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rev: Option<String>,
    /// Folder inside the repository holding `package.ron`, when it is not the
    /// root.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subdir: Option<String>,
}

/// What people who ran a package thought of it, in one number and a count.
///
/// **Absent means nobody has reviewed it**, which is why this is an `Option` and
/// not a score of zero: a package nobody has got to yet must not render as one
/// everybody hated.
#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub struct Rating {
    /// The plain mean, 1–5. Plain on purpose: a number the reader can
    /// reconstruct from the reviews on screen is worth more than a
    /// better-calibrated one they cannot.
    pub score: f32,
    /// How many reviews it is made of. A 5.0 from one person and a 4.6 from
    /// ninety are different claims and the count is what tells them apart.
    pub count: u32,
}

/// The neutral score an unproven package is pulled towards, and how many
/// reviews of pull it takes to escape it.
///
/// `PRIOR_WEIGHT` reviews at `PRIOR_SCORE` are added to everybody's tally before
/// ranking. Five is deliberately small — it is enough that one enthusiastic
/// friend cannot top the catalogue, and few enough that a genuinely good
/// package with a dozen reviews still gets there.
const PRIOR_SCORE: f32 = 3.5;
const PRIOR_WEIGHT: f32 = 5.0;

impl Rating {
    /// The score to **rank** by, which is not the score to **show**.
    ///
    /// The displayed number stays the plain mean, for the reason [`Rating`]
    /// gives: a reader can reconstruct it from the reviews in front of them. But
    /// ranking a catalogue on a plain mean puts every package with a single
    /// five-star review above every package with a track record, and a store
    /// whose top row is unproven is a store nobody trusts twice.
    ///
    /// So the mean is shown and a shrunk mean is sorted — which is the honest
    /// pairing, because the question "how good is this" and the question "how
    /// sure are we" have different answers and only one of them belongs on a
    /// star row.
    pub fn confidence(&self) -> f32 {
        let n = self.count as f32;
        (PRIOR_SCORE * PRIOR_WEIGHT + self.score * n) / (PRIOR_WEIGHT + n)
    }
}

/// One package in the catalogue.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Listing {
    pub id: String,
    pub name: String,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub author: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub homepage: Option<String>,
    #[serde(default)]
    pub keywords: Vec<String>,
    /// Which shelves the author put it on. Read **leniently**: a category this
    /// build has never heard of is dropped rather than failing the catalogue,
    /// which is what lets the list grow without stranding older editors.
    #[serde(default, deserialize_with = "lenient_categories", skip_serializing_if = "Vec::is_empty")]
    pub categories: Vec<Category>,
    /// What it demonstrably holds, derived by the publisher from the files
    /// themselves — see [`crate::contents`]. Unknown facet names are dropped for
    /// the same reason as unknown categories.
    #[serde(default, deserialize_with = "lenient_facets", skip_serializing_if = "Vec::is_empty")]
    pub contains: Vec<Facet>,
    /// The square image that IS this row in a grid. An absolute URL here — the
    /// catalogue is read by things that cannot clone the repository.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub thumbnail: Option<String>,
    /// A wide image for the package's own page.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub banner: Option<String>,
    /// Screenshots and videos, in the author's order.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub media: Vec<Media>,
    /// ISO date of the newest published version — what "recently updated" sorts
    /// on. A catalogue cannot be ordered by liveliness without it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub updated: Option<String>,
    /// How many times it has been installed, if anybody is counting.
    ///
    /// **Absent is not zero.** A registry that does not count downloads must not
    /// make every package on it look like one nobody has ever installed — the
    /// same rule as [`Rating`].
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub downloads: Option<u64>,
    /// The author's declared permissions, from the manifest of the newest
    /// listed version — a *claim*, advisory only. The consent gate that
    /// actually grants anything still reads the manifest off disk at install
    /// time; this is what lets the editor say "this will ask for network"
    /// before that moment (`floptle/0137`).
    ///
    /// **Absent is not "none"**, the same rule as [`Listing::downloads`]: it
    /// means the registry did not say, not that the package asks for nothing.
    /// A readable manifest always yields the key — `Some(vec![])` is the
    /// positive "declares none". Render nothing for `None`; only render "no
    /// permissions" for `Some(vec![])`, if that is ever worth saying.
    ///
    /// Read leniently, like [`Listing::categories`]: a permission kind this
    /// build has never heard of is dropped from the list rather than failing
    /// the whole field, or a newer engine adding a kind would strand every
    /// older one on an unparseable catalogue.
    #[serde(default, deserialize_with = "lenient_permissions", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<Vec<Permission>>,
    #[serde(default)]
    pub versions: Vec<Release>,
    /// Absent until somebody reviews it. Added after the reader shipped, which
    /// is safe because unknown fields are ignored and a missing one defaults —
    /// an older editor simply shows no score.
    ///
    /// Read leniently on purpose: see [`lenient_rating`].
    #[serde(default, deserialize_with = "lenient_rating", skip_serializing_if = "Option::is_none")]
    pub rating: Option<Rating>,
}

impl Listing {
    /// The newest release this engine can actually run — which is not always
    /// the newest release. A catalogue row that offers a version the editor
    /// will refuse on install is a row that wastes somebody's afternoon.
    ///
    /// [`matches_engine`](crate::VersionReq::matches_engine), not `matches`:
    /// the argument is the build in the developer's hands, not a candidate
    /// being chosen from a list. Under the strict rule a beta engine matched
    /// no `engine` bound at all, so the whole catalogue read "nothing for
    /// Floptle 0.85.0-rc3 yet" — every row, every package.
    pub fn best_for(&self, engine: &Version) -> Option<&Release> {
        self.versions
            .iter()
            .filter(|r| r.engine.as_ref().is_none_or(|req| req.matches_engine(engine)))
            .max_by(|a, b| a.version.cmp(&b.version))
    }

    /// The newest release, whatever engine it wants.
    pub fn newest(&self) -> Option<&Release> {
        self.versions.iter().max_by(|a, b| a.version.cmp(&b.version))
    }

    /// Does this row match a search box's contents? Case-insensitive over id,
    /// name, description and keywords, every whitespace-separated word having
    /// to match somewhere — so "grass terrain" finds a terrain package about
    /// grass and not every package about either.
    pub fn matches(&self, query: &str) -> bool {
        let q = query.trim().to_lowercase();
        if q.is_empty() {
            return true;
        }
        let hay = format!(
            "{} {} {} {} {} {}",
            self.id.to_lowercase(),
            self.name.to_lowercase(),
            self.author.to_lowercase(),
            self.description.to_lowercase(),
            self.keywords.join(" ").to_lowercase(),
            // Searching "audio" should find the Audio shelf, and "3d art" the
            // 3D one — the labels are what a person types, not `Art3D`.
            self.categories
                .iter()
                .map(|c| c.label().to_lowercase())
                .collect::<Vec<_>>()
                .join(" "),
        );
        q.split_whitespace().all(|w| hay.contains(w))
    }

    /// Does this row belong on **every** shelf in `wanted`? An empty `wanted`
    /// asks nothing and matches everything.
    pub fn in_categories(&self, wanted: &[Category]) -> bool {
        wanted.iter().all(|c| self.categories.contains(c))
    }

    /// Does this row hold **all** of `wanted`? Empty asks nothing.
    pub fn holds(&self, wanted: &[Facet]) -> bool {
        wanted.iter().all(|f| self.contains.contains(f))
    }
}

/// How a catalogue is ordered.
#[derive(Clone, Copy, PartialEq, Eq, Debug, Default)]
pub enum Sort {
    /// Newest published version first. The default, because it is the order that
    /// makes a catalogue read as a place where things are happening.
    #[default]
    Updated,
    /// Highest rated, then most-reviewed as the tie-break — a lone 5.0 does not
    /// outrank a 4.8 from ninety people.
    Rated,
    /// Most reviews.
    Reviewed,
    Name,
    Downloads,
}

impl Sort {
    pub const ALL: &'static [Sort] =
        &[Sort::Updated, Sort::Rated, Sort::Reviewed, Sort::Name, Sort::Downloads];

    pub fn label(self) -> &'static str {
        match self {
            Sort::Updated => "recently updated",
            Sort::Rated => "highest rated",
            Sort::Reviewed => "most reviewed",
            Sort::Name => "name",
            Sort::Downloads => "most installed",
        }
    }
}

/// Everything a browser asks the catalogue at once: what to look for, which
/// shelves, what it must hold, whether it has to run here, and in what order.
///
/// One struct rather than five arguments so the same question can be asked by
/// the editor's browser and by a test, and answered identically.
#[derive(Clone, Debug, Default)]
pub struct Query {
    pub search: String,
    pub categories: Vec<Category>,
    pub contains: Vec<Facet>,
    /// Drop rows with no version this engine can run. Off by default: a person
    /// browsing should be able to see what exists and learn that they need a
    /// newer engine, rather than have it silently withheld.
    pub compatible_only: Option<Version>,
    pub sort: Sort,
}

/// The whole catalogue.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct Index {
    #[serde(default)]
    pub packages: Vec<Listing>,
}

impl Index {
    pub fn parse(json: &str) -> Result<Index, String> {
        serde_json::from_str(json).map_err(|e| format!("the package catalogue would not read: {e}"))
    }

    /// Rows matching `query`, best matches first: an id or name that starts
    /// with the query beats one that merely contains it, then alphabetical.
    pub fn search(&self, query: &str) -> Vec<&Listing> {
        let q = query.trim().to_lowercase();
        let mut hits: Vec<&Listing> = self.packages.iter().filter(|l| l.matches(&q)).collect();
        hits.sort_by_key(|l| {
            let rank = if q.is_empty() {
                1
            } else if l.name.to_lowercase().starts_with(&q) || l.id.to_lowercase().starts_with(&q) {
                0
            } else {
                1
            };
            (rank, l.name.to_lowercase())
        });
        hits
    }

    pub fn find(&self, id: &str) -> Option<&Listing> {
        self.packages.iter().find(|l| l.id == id)
    }

    /// The rows a browser should draw, filtered and ordered by `q`.
    ///
    /// Search relevance still wins when there is a search: somebody who typed
    /// "grass" wants the grass package first, whatever the sort says. The sort
    /// orders everything the search did not already rank.
    pub fn query(&self, q: &Query) -> Vec<&Listing> {
        let needle = q.search.trim().to_lowercase();
        let mut hits: Vec<&Listing> = self
            .packages
            .iter()
            .filter(|l| l.matches(&needle))
            .filter(|l| l.in_categories(&q.categories))
            .filter(|l| l.holds(&q.contains))
            .filter(|l| match &q.compatible_only {
                Some(engine) => l.best_for(engine).is_some(),
                None => true,
            })
            .collect();

        // Rank first (0 = the query is a prefix of the name or id), then the
        // chosen order inside each rank.
        // 0 = the query is a prefix of the name or id. With no query nothing
        // outranks anything, so everything is rank 0 and the sort decides.
        let rank = |l: &Listing| -> u8 {
            let prefix = l.name.to_lowercase().starts_with(&needle)
                || l.id.to_lowercase().starts_with(&needle);
            u8::from(!(needle.is_empty() || prefix))
        };
        hits.sort_by(|a, b| {
            rank(a).cmp(&rank(b)).then_with(|| match q.sort {
                // Reverse ISO dates sort as reverse chronological, which is why
                // the field is a string and not parsed. A row with no date sorts
                // last rather than first — an unknown date is not "just now".
                Sort::Updated => b
                    .updated
                    .as_deref()
                    .unwrap_or("")
                    .cmp(a.updated.as_deref().unwrap_or("")),
                Sort::Rated => {
                    let key = |l: &Listing| l.rating.map(|r| (r.confidence(), r.count));
                    match (key(b), key(a)) {
                        (Some(x), Some(y)) => x
                            .0
                            .partial_cmp(&y.0)
                            .unwrap_or(std::cmp::Ordering::Equal)
                            .then(x.1.cmp(&y.1)),
                        // Unrated sorts after rated, never as a zero. (`a` is
                        // the second of the pair here — the match is flipped to
                        // make the whole comparison descending.)
                        (Some(_), None) => std::cmp::Ordering::Greater,
                        (None, Some(_)) => std::cmp::Ordering::Less,
                        (None, None) => std::cmp::Ordering::Equal,
                    }
                }
                Sort::Reviewed => b
                    .rating
                    .map(|r| r.count)
                    .unwrap_or(0)
                    .cmp(&a.rating.map(|r| r.count).unwrap_or(0)),
                Sort::Name => std::cmp::Ordering::Equal,
                Sort::Downloads => b.downloads.unwrap_or(0).cmp(&a.downloads.unwrap_or(0)),
            })
            // Name is always the final tie-break, so the same catalogue always
            // draws in the same order rather than in hash order.
            .then_with(|| a.name.to_lowercase().cmp(&b.name.to_lowercase()))
        });
        hits
    }

    /// How many rows would land on each shelf, given everything in `q` **except**
    /// the category filter itself.
    ///
    /// Counting with the other filters applied is the whole point: a count that
    /// ignores the search box tells you there are 40 audio packages and then
    /// shows you none.
    pub fn category_counts(&self, q: &Query) -> Vec<(Category, usize)> {
        let mut base = q.clone();
        base.categories = Vec::new();
        let rows = self.query(&base);
        Category::ALL
            .iter()
            .map(|c| (*c, rows.iter().filter(|l| l.categories.contains(c)).count()))
            .collect()
    }

    /// The same, for the derived facets.
    pub fn facet_counts(&self, q: &Query) -> Vec<(Facet, usize)> {
        let mut base = q.clone();
        base.contains = Vec::new();
        let rows = self.query(&base);
        Facet::ALL
            .iter()
            .map(|f| (*f, rows.iter().filter(|l| l.contains.contains(f)).count()))
            .collect()
    }
}

/// A rating that will not read is **no rating**, not a broken catalogue.
///
/// Without this, one malformed `rating` on one package fails the whole
/// `Index::parse` and every package disappears from Browse — a cosmetic field
/// taking down the entire catalogue. The shape that would do it is not
/// hypothetical: the reviews document already serialises an unreviewed package
/// as `"score": null`, and the same serialiser pointed at an index row would
/// emit `{"score": null, "count": 0}`, which is not an `f32`.
///
/// A star rating is the least important thing on the row. It must never be able
/// to hide the package it belongs to.
fn lenient_rating<'de, D>(d: D) -> Result<Option<Rating>, D::Error>
where
    D: Deserializer<'de>,
{
    let raw = Option::<serde_json::Value>::deserialize(d)?;
    Ok(raw.and_then(|v| serde_json::from_value::<Rating>(v).ok()))
}

/// A vocabulary this build does not know is a **word dropped**, never a
/// catalogue refused.
///
/// Both `categories` and `contains` are closed lists that will grow: the site
/// and the editor ship on different days, so there is always a window where the
/// catalogue names a shelf the reader has not heard of. The only acceptable
/// behaviour in that window is to render the package without that one chip.
/// Anything stricter means adding a category takes every older editor's Browse
/// tab down with it.
/// The value is read as an untyped `Value` first, not as a `Vec` of them: a
/// field that is not a list at all — `"categories": "Art3D"`, or `null` — must
/// also cost only itself, and deserializing straight into a `Vec` fails the
/// whole document on exactly that shape.
fn lenient_list<'de, D, T>(d: D) -> Result<Vec<T>, D::Error>
where
    D: Deserializer<'de>,
    T: serde::de::DeserializeOwned,
{
    let raw = Option::<serde_json::Value>::deserialize(d)?;
    let Some(serde_json::Value::Array(items)) = raw else { return Ok(Vec::new()) };
    Ok(items.into_iter().filter_map(|v| serde_json::from_value::<T>(v).ok()).collect())
}

fn lenient_categories<'de, D: Deserializer<'de>>(d: D) -> Result<Vec<Category>, D::Error> {
    lenient_list(d)
}

fn lenient_facets<'de, D: Deserializer<'de>>(d: D) -> Result<Vec<Facet>, D::Error> {
    lenient_list(d)
}

/// Unlike `categories`/`contains` — plain `Vec`s, where absent and empty read
/// the same — this has to keep `None` (the registry did not say) apart from
/// `Some(vec![])` (declares none), so it cannot just be `lenient_list` behind
/// `#[serde(default)]`: that would collapse both onto an empty `Vec`. `#[serde(default)]`
/// on the field already gives `None` for an ABSENT key without this function
/// running at all; this only has to cover a key that IS present — `null`
/// reads the same as absent, an array keeps whatever entries this build
/// recognises (unlike `lenient_list`, one bad entry does not need to be able
/// to sink the array — there simply are so few permission kinds that a
/// single genuinely-malformed one is likely the whole list).
///
/// **Present-but-unreadable is not the same fact as "declares nothing", and
/// must not read as one** — this field's only reason to exist is warning
/// someone before they install a package, and collapsing "we could not tell
/// what this asked for" into the safest possible answer defeats that
/// (`floptle/0137`, found by an adversarial review re-reading this card
/// before it shipped). So a value that is present but not an array at all,
/// or an array where EVERY entry failed to parse (a genuinely empty array is
/// still a clean, explicit "declares none" and is left alone), reads as
/// [`Permission::ALL`] instead of `None` — assume the maximum until this
/// catalogue entry is fixed, the same "err toward the alarming answer, not
/// the quiet one" call this session already made for a body's sleep state.
fn lenient_permissions<'de, D: Deserializer<'de>>(
    d: D,
) -> Result<Option<Vec<Permission>>, D::Error> {
    let raw = Option::<serde_json::Value>::deserialize(d)?;
    match raw {
        None | Some(serde_json::Value::Null) => Ok(None),
        Some(serde_json::Value::Array(items)) => {
            let declared_something = !items.is_empty();
            let parsed: Vec<Permission> =
                items.into_iter().filter_map(|v| serde_json::from_value::<Permission>(v).ok()).collect();
            if parsed.is_empty() && declared_something {
                Ok(Some(Permission::ALL.to_vec()))
            } else {
                Ok(Some(parsed))
            }
        }
        Some(_) => Ok(Some(Permission::ALL.to_vec())),
    }
}

/// One person's word on a package they ran.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct Review {
    #[serde(default)]
    pub author: String,
    /// 1–5.
    #[serde(default)]
    pub rating: u32,
    /// May be empty. A rating with no words is a perfectly good review, and
    /// demanding prose gets you fewer and worse ones.
    #[serde(default)]
    pub body: String,
    /// The version the reviewer actually had installed. The editor knows this
    /// for certain, which makes it the most trustworthy field here — a review of
    /// 1.0.0 should not silently read as a review of 3.0.0.
    #[serde(default)]
    pub version: String,
    #[serde(default)]
    pub date: String,
    #[serde(default)]
    pub edited: bool,
}

/// Every review of one package — served as its own document so reading them
/// needs no account and caches like the catalogue.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct Reviews {
    #[serde(default)]
    pub id: String,
    #[serde(default)]
    pub count: u32,
    #[serde(default)]
    pub reviews: Vec<Review>,
}

impl Reviews {
    pub fn parse(json: &str) -> Result<Reviews, String> {
        serde_json::from_str(json).map_err(|e| format!("the reviews would not read: {e}"))
    }

    /// The mean of what is actually here, for showing beside a list the reader
    /// can count themselves. The catalogue's own `Rating` is authoritative —
    /// this is for when only the document has been fetched.
    pub fn mean(&self) -> Option<f32> {
        let scored: Vec<u32> = self.reviews.iter().map(|r| r.rating).filter(|r| *r > 0).collect();
        if scored.is_empty() {
            return None;
        }
        Some(scored.iter().sum::<u32>() as f32 / scored.len() as f32)
    }
}

/// Where a package's reviews live, derived from whichever catalogue is in use.
///
/// The last segment of the index URL is replaced, so a studio pointing at its
/// own `index.json` gets its own reviews rather than fopull.com's — the same
/// reason the index URL is a setting at all.
pub fn reviews_url_for(index_url: &str, id: &str) -> String {
    let base = index_url.trim_end_matches('/');
    let cut = base.rfind('/').map(|i| &base[..i]).unwrap_or(base);
    format!("{cut}/reviews/{id}.json")
}

/// Where a person goes to write a review of `id`, and where they go to read
/// about the package at all.
///
/// **Always fopull.com**, whatever registry the catalogue points at. Writing a
/// review means signing in, and the editor will not send an account anywhere
/// but home — a private registry can serve its own listings and its own
/// reviews, but it cannot collect one. Somebody running their own catalogue
/// gets a link that goes to the public site, which is the honest outcome: there
/// is nowhere else it could safely go.
pub fn review_page_for(id: &str) -> String {
    format!("https://fopull.com/packages/{id}/review")
}

/// The package's own page on fopull.com — what it is, its versions, and every
/// review of it.
pub fn package_page_for(id: &str) -> String {
    format!("https://fopull.com/packages/{id}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_review_link_goes_home_whatever_registry_is_set() {
        // A private registry serves listings and reviews; it cannot take one,
        // because the editor will not send an account token off fopull.com.
        assert_eq!(
            review_page_for("com.example.grass"),
            "https://fopull.com/packages/com.example.grass/review"
        );
        assert_eq!(
            package_page_for("com.example.grass"),
            "https://fopull.com/packages/com.example.grass"
        );
    }

    const SAMPLE: &str = r#"{
        "packages": [
            { "id": "com.example.grass", "name": "Grass Tools",
              "description": "Scatter and paint grass on terrain",
              "author": "Example", "keywords": ["terrain", "vegetation"],
              "versions": [
                {"version": "1.0.0", "git": "https://x/g.git", "rev": "v1.0.0"},
                {"version": "2.0.0", "engine": ">=9.0.0", "git": "https://x/g.git", "rev": "v2.0.0"},
                {"version": "1.4.0", "engine": ">=0.55.0", "git": "https://x/g.git", "rev": "v1.4.0"}
              ] },
            { "id": "com.other.audio", "name": "Audio Kit",
              "description": "Reverb impulse responses", "author": "Other",
              "versions": [{"version": "0.3.0", "git": "https://x/a.git"}] }
        ]
    }"#;

    #[test]
    fn parses_the_catalogue() {
        let idx = Index::parse(SAMPLE).unwrap();
        assert_eq!(idx.packages.len(), 2);
        assert_eq!(idx.find("com.example.grass").unwrap().name, "Grass Tools");
    }

    /// The row must not offer a version this engine will refuse on install.
    #[test]
    fn the_offered_version_is_the_newest_this_engine_can_run() {
        let idx = Index::parse(SAMPLE).unwrap();
        let grass = idx.find("com.example.grass").unwrap();
        assert_eq!(grass.newest().unwrap().version, Version::new(2, 0, 0));
        let best = grass.best_for(&Version::new(0, 55, 0)).unwrap();
        assert_eq!(best.version, Version::new(1, 4, 0));
        assert_eq!(best.rev.as_deref(), Some("v1.4.0"));
    }

    #[test]
    fn a_release_with_no_engine_range_runs_anywhere() {
        let idx = Index::parse(SAMPLE).unwrap();
        let audio = idx.find("com.other.audio").unwrap();
        assert!(audio.best_for(&Version::new(0, 1, 0)).is_some());
    }

    #[test]
    fn search_needs_every_word_to_match() {
        let idx = Index::parse(SAMPLE).unwrap();
        assert_eq!(idx.search("grass").len(), 1);
        assert_eq!(idx.search("grass terrain").len(), 1);
        assert_eq!(idx.search("grass reverb").len(), 0);
        assert_eq!(idx.search("").len(), 2);
        // Keywords count, and so does the id.
        assert_eq!(idx.search("vegetation").len(), 1);
        assert_eq!(idx.search("com.other").len(), 1);
    }

    #[test]
    fn a_name_that_starts_with_the_query_sorts_first() {
        let idx = Index::parse(
            r#"{"packages":[
                {"id":"com.a.b","name":"Zebra grass","versions":[]},
                {"id":"com.c.d","name":"Grass Tools","versions":[]}
            ]}"#,
        )
        .unwrap();
        let hits = idx.search("grass");
        assert_eq!(hits[0].name, "Grass Tools");
    }

    #[test]
    fn a_malformed_catalogue_says_so_in_words() {
        let err = Index::parse("{ nope").unwrap_err();
        assert!(err.contains("catalogue"), "{err}");
    }

    /// A package nobody has reviewed must not read as one everybody hated, so
    /// the absence of a rating is a different thing from a score of zero.
    #[test]
    fn an_unreviewed_package_has_no_rating_rather_than_a_zero() {
        let idx = Index::parse(SAMPLE).unwrap();
        assert!(idx.find("com.other.audio").unwrap().rating.is_none());

        let rated = Index::parse(
            r#"{"packages":[{"id":"a.b","name":"A","rating":{"score":4.3,"count":12},"versions":[]}]}"#,
        )
        .unwrap();
        let r = rated.find("a.b").unwrap().rating.unwrap();
        assert_eq!((r.score, r.count), (4.3, 12));
    }

    /// The field was added after the reader shipped. Every already-published
    /// catalogue must keep parsing, and a catalogue carrying it must not break
    /// an editor that predates it — which is the same property, tested from
    /// both ends.
    #[test]
    fn a_catalogue_without_ratings_still_parses_and_one_with_extra_fields_does_too() {
        assert!(Index::parse(SAMPLE).is_ok());
        let future = Index::parse(
            r#"{"packages":[{"id":"a.b","name":"A","versions":[],
                 "rating":{"score":5.0,"count":1},"somethingElse":{"x":1}}],"alsoNew":true}"#,
        )
        .unwrap();
        assert_eq!(future.packages.len(), 1);
    }

    /// A cosmetic field must never be able to empty the catalogue. The
    /// `"score": null` shape is exactly what the reviews document already emits
    /// for an unreviewed package, so this is one serialiser change away from
    /// being real rather than a hypothetical.
    #[test]
    fn a_rating_that_will_not_read_costs_its_own_stars_and_nothing_else() {
        for bad in [
            r#""rating":{"score":null,"count":0}"#,
            r#""rating":{"count":3}"#,
            r#""rating":"4.5""#,
            r#""rating":[]"#,
            r#""rating":null"#,
        ] {
            let json = format!(
                r#"{{"packages":[
                     {{"id":"a.b","name":"A","versions":[],{bad}}},
                     {{"id":"c.d","name":"C","versions":[],"rating":{{"score":4.5,"count":2}}}}
                   ]}}"#
            );
            let idx = Index::parse(&json)
                .unwrap_or_else(|e| panic!("a bad rating must not fail the catalogue ({bad}): {e}"));
            assert_eq!(idx.packages.len(), 2, "{bad}");
            assert!(idx.find("a.b").unwrap().rating.is_none(), "{bad}");
            // …and the package beside it keeps its own perfectly good rating.
            assert_eq!(idx.find("c.d").unwrap().rating.unwrap().count, 2, "{bad}");
        }
    }

    #[test]
    fn reviews_read_and_average_what_is_actually_there() {
        let r = Reviews::parse(
            r#"{"id":"a.b","count":3,"reviews":[
                {"author":"X","rating":5,"body":"good","version":"1.0.0","date":"2026-08-12"},
                {"author":"Y","rating":4,"body":"","version":"1.1.0","date":"2026-08-12"},
                {"author":"Z","rating":3,"body":"meh","version":"1.1.0","date":"2026-08-13","edited":true}
            ]}"#,
        )
        .unwrap();
        assert_eq!(r.reviews.len(), 3);
        assert_eq!(r.mean(), Some(4.0));
        // An empty body is a real review, not a malformed one.
        assert_eq!(r.reviews[1].body, "");
        assert!(r.reviews[2].edited);
        // Nothing to average is None, not 0.0.
        assert_eq!(Reviews::default().mean(), None);
    }

    /// Reviews follow whichever catalogue is in use, so a studio on its own
    /// registry does not read fopull.com's reviews of a package it has never
    /// heard of.
    #[test]
    fn reviews_live_beside_the_catalogue_they_belong_to() {
        assert_eq!(
            reviews_url_for(DEFAULT_INDEX_URL, "com.example.grass"),
            "https://fopull.com/packages/reviews/com.example.grass.json"
        );
        assert_eq!(
            reviews_url_for("https://studio.internal/floptle/catalogue.json", "a.b"),
            "https://studio.internal/floptle/reviews/a.b.json"
        );
    }

    #[test]
    fn round_trips() {
        let idx = Index::parse(SAMPLE).unwrap();
        let text = serde_json::to_string(&idx).unwrap();
        assert_eq!(Index::parse(&text).unwrap(), idx);
    }

    // ---- the catalogue an art package needs (0134) -------------------------

    const RICH: &str = r#"{"packages":[
        {"id":"com.fopull.brutalist","name":"Brutalist Kit","author":"Fopull",
         "description":"Concrete blocks","categories":["Art3D"],
         "contains":["models","textures","prefabs"],
         "thumbnail":"https://x/icon.png","banner":"https://x/wide.png",
         "media":[{"image":"https://x/a.png","caption":"Overview"},
                  {"video":"https://youtu.be/z","poster":"https://x/p.png"}],
         "updated":"2026-08-14","downloads":1284,
         "rating":{"score":4.8,"count":90},
         "permissions":["Network","Browser"],
         "versions":[{"version":"1.0.0","git":"https://x/b.git","rev":"v1.0.0"}]},
        {"id":"com.other.sfx","name":"Field SFX","author":"Other",
         "categories":["Audio"],"contains":["audio"],"updated":"2026-08-01",
         "rating":{"score":5.0,"count":1},
         "versions":[{"version":"0.2.0","git":"https://x/s.git"}]},
        {"id":"com.third.tool","name":"Alpha Tool","author":"Third",
         "categories":["EditorTool","Scripts"],"contains":["editor","scripts"],
         "updated":"2026-07-02",
         "versions":[{"version":"1.0.0","engine":">=9.0.0","git":"https://x/t.git"}]}
    ]}"#;

    #[test]
    fn a_listing_carries_everything_an_art_package_needs_to_show_itself() {
        let idx = Index::parse(RICH).unwrap();
        let kit = idx.find("com.fopull.brutalist").unwrap();
        assert_eq!(kit.categories, vec![Category::Art3D]);
        assert_eq!(kit.contains, vec![Facet::Models, Facet::Textures, Facet::Prefabs]);
        assert_eq!(kit.thumbnail.as_deref(), Some("https://x/icon.png"));
        assert_eq!(kit.media.len(), 2);
        assert_eq!(kit.media[0].caption, "Overview");
        assert!(kit.media[1].is_video());
        assert_eq!(kit.media[1].still(), Some("https://x/p.png"));
        assert_eq!(kit.updated.as_deref(), Some("2026-08-14"));
        assert_eq!(kit.downloads, Some(1284));
        // …and a listing with none of it still reads, which is every listing
        // published before this shipped.
        assert!(Index::parse(SAMPLE).unwrap().find("com.other.audio").unwrap().categories.is_empty());
    }

    /// The window where the site knows a shelf the editor does not is
    /// permanent — they ship on different days. It must cost one chip, never
    /// the catalogue.
    #[test]
    fn a_category_this_build_has_never_heard_of_is_dropped_not_fatal() {
        let idx = Index::parse(
            r#"{"packages":[{"id":"a.b","name":"A","versions":[],
                 "categories":["Art3D","Holograms","Audio"],
                 "contains":["models","neuralnets"]}]}"#,
        )
        .expect("an unknown category must not fail the catalogue");
        let row = idx.find("a.b").unwrap();
        assert_eq!(row.categories, vec![Category::Art3D, Category::Audio]);
        assert_eq!(row.contains, vec![Facet::Models]);

        // The same for shapes that are not lists of strings at all.
        for bad in [r#""categories":"Art3D""#, r#""categories":null"#, r#""contains":{}"#] {
            let json = format!(r#"{{"packages":[{{"id":"a.b","name":"A","versions":[],{bad}}}]}}"#);
            assert_eq!(Index::parse(&json).unwrap().packages.len(), 1, "{bad}");
        }
    }

    #[test]
    fn filters_are_and_not_or() {
        let idx = Index::parse(RICH).unwrap();
        let q = |c: Vec<Category>, f: Vec<Facet>| Query {
            categories: c,
            contains: f,
            ..Default::default()
        };
        // One shelf.
        assert_eq!(idx.query(&q(vec![Category::Art3D], vec![])).len(), 1);
        // Two shelves means BOTH, which only the tool is on.
        let both = idx.query(&q(vec![Category::EditorTool, Category::Scripts], vec![]));
        assert_eq!(both.len(), 1);
        assert_eq!(both[0].id, "com.third.tool");
        // A shelf nobody is on.
        assert!(idx.query(&q(vec![Category::Fonts], vec![])).is_empty());
        // "I need SFX" is a contains question, not a shelf question.
        let audio = idx.query(&q(vec![], vec![Facet::Audio]));
        assert_eq!(audio.len(), 1);
        assert_eq!(audio[0].id, "com.other.sfx");
        // Nothing asked, everything back.
        assert_eq!(idx.query(&Query::default()).len(), 3);
    }

    #[test]
    fn every_sort_orders_what_it_says_and_puts_the_unknown_last() {
        let idx = Index::parse(RICH).unwrap();
        let by = |s: Sort| -> Vec<String> {
            idx.query(&Query { sort: s, ..Default::default() })
                .iter()
                .map(|l| l.id.clone())
                .collect()
        };
        assert_eq!(by(Sort::Updated)[0], "com.fopull.brutalist");
        assert_eq!(by(Sort::Updated)[2], "com.third.tool");
        assert_eq!(by(Sort::Name)[0], "com.third.tool", "Alpha Tool sorts first by name");
        assert_eq!(by(Sort::Downloads)[0], "com.fopull.brutalist");
        assert_eq!(by(Sort::Reviewed)[0], "com.fopull.brutalist", "90 reviews beats 1");

        // A 5.0 from one person must not outrank a 4.8 from ninety.
        let rated = by(Sort::Rated);
        assert_eq!(rated[0], "com.fopull.brutalist", "4.8 from ninety beats 5.0 from one");
        assert_eq!(rated[1], "com.other.sfx");
        // …and the unrated package sorts last rather than as a zero.
        assert_eq!(rated[2], "com.third.tool");
    }

    /// The number on the star row and the number the catalogue is ordered by
    /// are deliberately not the same number.
    #[test]
    fn the_shown_score_is_plain_and_the_ranked_one_is_not() {
        let lone = Rating { score: 5.0, count: 1 };
        let proven = Rating { score: 4.8, count: 90 };
        assert_eq!(lone.score, 5.0, "what is shown stays the plain mean");
        assert!(
            proven.confidence() > lone.confidence(),
            "{} vs {}",
            proven.confidence(),
            lone.confidence()
        );
        // A package with enough reviews sits essentially at its own mean.
        assert!((proven.confidence() - 4.8).abs() < 0.1, "{}", proven.confidence());
        // Nobody is dragged below the prior by having few reviews and a good
        // score — shrinkage pulls towards neutral, it does not punish.
        assert!(lone.confidence() > PRIOR_SCORE);
        // …and a bad package with one review is not flattered up to neutral.
        assert!(Rating { score: 1.0, count: 1 }.confidence() < PRIOR_SCORE);
    }

    /// Somebody who typed "brutalist" wants the brutalist package first, even
    /// when the sort would have put something else there.
    #[test]
    fn a_search_still_ranks_ahead_of_the_sort() {
        let idx = Index::parse(RICH).unwrap();
        let hits = idx.query(&Query {
            search: "field".into(),
            sort: Sort::Updated,
            ..Default::default()
        });
        assert_eq!(hits[0].id, "com.other.sfx");
        // Search reaches the author and the category label too.
        assert_eq!(idx.query(&Query { search: "fopull".into(), ..Default::default() }).len(), 1);
        assert_eq!(idx.query(&Query { search: "audio".into(), ..Default::default() })[0].id,
                   "com.other.sfx");
    }

    /// Withholding a package because this engine is too old is a decision a
    /// person should make, so it is off unless asked for.
    #[test]
    fn engine_compatibility_is_a_filter_you_turn_on() {
        let idx = Index::parse(RICH).unwrap();
        assert_eq!(idx.query(&Query::default()).len(), 3);
        let only = idx.query(&Query {
            compatible_only: Some(Version::new(0, 57, 0)),
            ..Default::default()
        });
        assert_eq!(only.len(), 2, "the >=9.0.0 tool is the one that cannot run here");
        assert!(only.iter().all(|l| l.id != "com.third.tool"));
    }

    /// A count that ignores the search box promises rows it will not show.
    #[test]
    fn shelf_counts_respect_every_filter_except_their_own() {
        let idx = Index::parse(RICH).unwrap();
        let q = Query { search: "kit".into(), ..Default::default() };
        let counts = idx.category_counts(&q);
        let of = |c: Category| counts.iter().find(|(k, _)| *k == c).unwrap().1;
        assert_eq!(of(Category::Art3D), 1);
        assert_eq!(of(Category::Audio), 0, "the SFX pack does not match 'kit'");

        // Picking a shelf must not zero out the other shelves' counts, or the
        // filter becomes a one-way door.
        let picked = Query { categories: vec![Category::Art3D], ..Default::default() };
        let counts = idx.category_counts(&picked);
        assert_eq!(counts.iter().find(|(k, _)| *k == Category::Audio).unwrap().1, 1);

        let facets = idx.facet_counts(&Query::default());
        assert_eq!(facets.iter().find(|(k, _)| *k == Facet::Models).unwrap().1, 1);
        assert_eq!(facets.iter().find(|(k, _)| *k == Facet::Editor).unwrap().1, 1);
    }

    #[test]
    fn a_rich_listing_round_trips_and_omits_what_it_does_not_have() {
        let idx = Index::parse(RICH).unwrap();
        let text = serde_json::to_string(&idx).unwrap();
        assert_eq!(Index::parse(&text).unwrap(), idx);
        // Absent stays absent — a registry that does not count installs must not
        // publish "0 downloads" for every package on it.
        assert!(!text.contains(r#""downloads":null"#));
        // Same for permissions: a package that declared some round-trips them...
        assert_eq!(
            idx.find("com.fopull.brutalist").unwrap().permissions,
            Some(vec![Permission::Network, Permission::Browser])
        );
        assert!(!text.contains(r#""permissions":null"#));
        // …and one that never named the field stays silent about it, not "[]".
        assert!(idx.find("com.other.sfx").unwrap().permissions.is_none());
        let bare = serde_json::to_string(&Index::parse(SAMPLE).unwrap()).unwrap();
        assert!(!bare.contains("categories"), "{bare}");
        assert!(!bare.contains("thumbnail"), "{bare}");
        assert!(!bare.contains("permissions"), "{bare}");
    }

    // ---- permissions (0137) -------------------------------------------------

    /// The same "absent is not zero" rule `rating`/`downloads` follow, with one
    /// more state: an author who ran the publisher and asks for nothing gets to
    /// SAY so (`Some(vec![])`), which reads differently from a registry that
    /// simply never mentioned the field (`None`).
    #[test]
    fn permissions_absent_is_none_and_declaring_none_is_some_empty() {
        let idx = Index::parse(SAMPLE).unwrap();
        assert!(
            idx.find("com.other.audio").unwrap().permissions.is_none(),
            "a listing that never named permissions must not read as \"asks for nothing\""
        );

        let declared = Index::parse(
            r#"{"packages":[
                 {"id":"a.b","name":"A","versions":[],"permissions":[]},
                 {"id":"c.d","name":"C","versions":[],"permissions":["Files"]}
               ]}"#,
        )
        .unwrap();
        assert_eq!(
            declared.find("a.b").unwrap().permissions,
            Some(vec![]),
            "an explicit empty array is the positive \"declares none\""
        );
        assert_eq!(declared.find("c.d").unwrap().permissions, Some(vec![Permission::Files]));
    }

    /// Verbatim pass-through with unknown kinds dropped, not fatal — the same
    /// contract `categories`/`contains` already keep, so a newer engine's
    /// permission kind cannot strand an older one on an unparseable catalogue.
    #[test]
    fn a_permission_this_build_has_never_heard_of_is_dropped_not_fatal() {
        let idx = Index::parse(
            r#"{"packages":[{"id":"a.b","name":"A","versions":[],
                 "permissions":["Network","MindControl","Browser"]}]}"#,
        )
        .expect("an unknown permission must not fail the catalogue");
        assert_eq!(
            idx.find("a.b").unwrap().permissions,
            Some(vec![Permission::Network, Permission::Browser])
        );

        // Shapes that are not a list of strings at all must not sink the
        // catalogue either — the same class of defect `rating`'s
        // `"score":null` guard exists for.
        for bad in [
            r#""permissions":"Network""#,
            r#""permissions":null"#,
            r#""permissions":{}"#,
            r#""permissions":[1,2,3]"#,
        ] {
            let json = format!(
                r#"{{"packages":[
                     {{"id":"a.b","name":"A","versions":[],{bad}}},
                     {{"id":"c.d","name":"C","versions":[],"permissions":["Files"]}}
                   ]}}"#
            );
            let idx = Index::parse(&json)
                .unwrap_or_else(|e| panic!("a bad permissions field must not fail the catalogue ({bad}): {e}"));
            assert_eq!(idx.packages.len(), 2, "{bad}");
            // …and the package beside it keeps its own perfectly good list.
            assert_eq!(idx.find("c.d").unwrap().permissions, Some(vec![Permission::Files]), "{bad}");
        }
    }

    /// The chip this field exists to drive (`permission_chip`,
    /// `floptle-editor/src/packages_ui.rs`) shows nothing when `permissions`
    /// is `None`. A value that is PRESENT but unreadable must not resolve to
    /// `None` too, or the one field whose entire job is warning someone before
    /// they install something reads as "nothing to see here" on exactly the
    /// listings it could least afford to (`floptle/0137`).
    #[test]
    fn a_permissions_field_this_reader_cannot_understand_reads_as_declaring_everything() {
        for bad in [r#""permissions":"Network""#, r#""permissions":{}"#, r#""permissions":[1,2,3]"#] {
            let json = format!(r#"{{"packages":[{{"id":"a.b","name":"A","versions":[],{bad}}}]}}"#);
            let idx = Index::parse(&json).expect("a bad permissions field must not fail the catalogue");
            assert_eq!(
                idx.find("a.b").unwrap().permissions,
                Some(Permission::ALL.to_vec()),
                "{bad}: unreadable must warn about everything, not nothing"
            );
        }

        // An explicit, genuinely empty list is a clean answer and must stay
        // exactly that — "declares none" is not the same fact as "unreadable".
        let idx = Index::parse(r#"{"packages":[{"id":"a.b","name":"A","versions":[],"permissions":[]}]}"#)
            .unwrap();
        assert_eq!(idx.find("a.b").unwrap().permissions, Some(vec![]));
    }
}
