//! The registry index — the catalogue the ✚ Browse tab reads.
//!
//! One JSON document, served over HTTP, listing packages and the versions each
//! one has published. JSON rather than RON because it is a *web* file: it is
//! generated by the site, cached by a CDN, and read by things that are not this
//! editor.
//!
//! ```json
//! { "packages": [ {
//!     "id": "com.example.grass", "name": "Grass Tools",
//!     "description": "…", "author": "Example", "keywords": ["terrain"],
//!     "versions": [ { "version": "1.2.0", "engine": ">=0.55.0",
//!                     "git": "https://github.com/example/grass.git", "rev": "v1.2.0" } ]
//! } ] }
//! ```
//!
//! Every published version says **where to get it**, so installing from the
//! catalogue is the Git path with the URL filled in — there is no second
//! download-and-unpack mechanism to get wrong, and a package listed here can be
//! installed by hand from the same URL by anybody who would rather not use the
//! browser.
//!
//! Fetching is the caller's job. This module parses, searches and sorts; it
//! opens no sockets, which is what makes it testable.

use serde::{Deserialize, Serialize};

use crate::version::{Version, VersionReq};

/// Where the catalogue lives. Overridable per install for a private registry.
pub const DEFAULT_INDEX_URL: &str = "https://fopull.com/packages/index.json";

/// One published version of a package.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Release {
    pub version: Version,
    /// Engine range, as in the manifest. Absent = any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub engine: Option<VersionReq>,
    /// The repository to clone.
    pub git: String,
    /// Branch, tag or commit. Absent = the default branch, which is a moving
    /// target — a published release should name one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rev: Option<String>,
    /// Folder inside the repository holding `package.ron`, when it is not the
    /// root.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subdir: Option<String>,
}

/// What people who ran a package thought of it, in one number and a count.
///
/// **Absent means nobody has reviewed it**, which is why this is an `Option` and
/// not a score of zero: a package nobody has got to yet must not render as one
/// everybody hated.
#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub struct Rating {
    /// The plain mean, 1–5. Plain on purpose: a number the reader can
    /// reconstruct from the reviews on screen is worth more than a
    /// better-calibrated one they cannot.
    pub score: f32,
    /// How many reviews it is made of. A 5.0 from one person and a 4.6 from
    /// ninety are different claims and the count is what tells them apart.
    pub count: u32,
}

/// One package in the catalogue.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Listing {
    pub id: String,
    pub name: String,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub author: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub homepage: Option<String>,
    #[serde(default)]
    pub keywords: Vec<String>,
    #[serde(default)]
    pub versions: Vec<Release>,
    /// Absent until somebody reviews it. Added after the reader shipped, which
    /// is safe because unknown fields are ignored and a missing one defaults —
    /// an older editor simply shows no score.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rating: Option<Rating>,
}

impl Listing {
    /// The newest release this engine can actually run — which is not always
    /// the newest release. A catalogue row that offers a version the editor
    /// will refuse on install is a row that wastes somebody's afternoon.
    pub fn best_for(&self, engine: &Version) -> Option<&Release> {
        self.versions
            .iter()
            .filter(|r| r.engine.as_ref().is_none_or(|req| req.matches(engine)))
            .max_by(|a, b| a.version.cmp(&b.version))
    }

    /// The newest release, whatever engine it wants.
    pub fn newest(&self) -> Option<&Release> {
        self.versions.iter().max_by(|a, b| a.version.cmp(&b.version))
    }

    /// Does this row match a search box's contents? Case-insensitive over id,
    /// name, description and keywords, every whitespace-separated word having
    /// to match somewhere — so "grass terrain" finds a terrain package about
    /// grass and not every package about either.
    pub fn matches(&self, query: &str) -> bool {
        let q = query.trim().to_lowercase();
        if q.is_empty() {
            return true;
        }
        let hay = format!(
            "{} {} {} {}",
            self.id.to_lowercase(),
            self.name.to_lowercase(),
            self.description.to_lowercase(),
            self.keywords.join(" ").to_lowercase()
        );
        q.split_whitespace().all(|w| hay.contains(w))
    }
}

/// The whole catalogue.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct Index {
    #[serde(default)]
    pub packages: Vec<Listing>,
}

impl Index {
    pub fn parse(json: &str) -> Result<Index, String> {
        serde_json::from_str(json).map_err(|e| format!("the package catalogue would not read: {e}"))
    }

    /// Rows matching `query`, best matches first: an id or name that starts
    /// with the query beats one that merely contains it, then alphabetical.
    pub fn search(&self, query: &str) -> Vec<&Listing> {
        let q = query.trim().to_lowercase();
        let mut hits: Vec<&Listing> = self.packages.iter().filter(|l| l.matches(&q)).collect();
        hits.sort_by_key(|l| {
            let rank = if q.is_empty() {
                1
            } else if l.name.to_lowercase().starts_with(&q) || l.id.to_lowercase().starts_with(&q) {
                0
            } else {
                1
            };
            (rank, l.name.to_lowercase())
        });
        hits
    }

    pub fn find(&self, id: &str) -> Option<&Listing> {
        self.packages.iter().find(|l| l.id == id)
    }
}

/// One person's word on a package they ran.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct Review {
    #[serde(default)]
    pub author: String,
    /// 1–5.
    #[serde(default)]
    pub rating: u32,
    /// May be empty. A rating with no words is a perfectly good review, and
    /// demanding prose gets you fewer and worse ones.
    #[serde(default)]
    pub body: String,
    /// The version the reviewer actually had installed. The editor knows this
    /// for certain, which makes it the most trustworthy field here — a review of
    /// 1.0.0 should not silently read as a review of 3.0.0.
    #[serde(default)]
    pub version: String,
    #[serde(default)]
    pub date: String,
    #[serde(default)]
    pub edited: bool,
}

/// Every review of one package — served as its own document so reading them
/// needs no account and caches like the catalogue.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct Reviews {
    #[serde(default)]
    pub id: String,
    #[serde(default)]
    pub count: u32,
    #[serde(default)]
    pub reviews: Vec<Review>,
}

impl Reviews {
    pub fn parse(json: &str) -> Result<Reviews, String> {
        serde_json::from_str(json).map_err(|e| format!("the reviews would not read: {e}"))
    }

    /// The mean of what is actually here, for showing beside a list the reader
    /// can count themselves. The catalogue's own `Rating` is authoritative —
    /// this is for when only the document has been fetched.
    pub fn mean(&self) -> Option<f32> {
        let scored: Vec<u32> = self.reviews.iter().map(|r| r.rating).filter(|r| *r > 0).collect();
        if scored.is_empty() {
            return None;
        }
        Some(scored.iter().sum::<u32>() as f32 / scored.len() as f32)
    }
}

/// Where a package's reviews live, derived from whichever catalogue is in use.
///
/// The last segment of the index URL is replaced, so a studio pointing at its
/// own `index.json` gets its own reviews rather than fopull.com's — the same
/// reason the index URL is a setting at all.
pub fn reviews_url_for(index_url: &str, id: &str) -> String {
    let base = index_url.trim_end_matches('/');
    let cut = base.rfind('/').map(|i| &base[..i]).unwrap_or(base);
    format!("{cut}/reviews/{id}.json")
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = r#"{
        "packages": [
            { "id": "com.example.grass", "name": "Grass Tools",
              "description": "Scatter and paint grass on terrain",
              "author": "Example", "keywords": ["terrain", "vegetation"],
              "versions": [
                {"version": "1.0.0", "git": "https://x/g.git", "rev": "v1.0.0"},
                {"version": "2.0.0", "engine": ">=9.0.0", "git": "https://x/g.git", "rev": "v2.0.0"},
                {"version": "1.4.0", "engine": ">=0.55.0", "git": "https://x/g.git", "rev": "v1.4.0"}
              ] },
            { "id": "com.other.audio", "name": "Audio Kit",
              "description": "Reverb impulse responses", "author": "Other",
              "versions": [{"version": "0.3.0", "git": "https://x/a.git"}] }
        ]
    }"#;

    #[test]
    fn parses_the_catalogue() {
        let idx = Index::parse(SAMPLE).unwrap();
        assert_eq!(idx.packages.len(), 2);
        assert_eq!(idx.find("com.example.grass").unwrap().name, "Grass Tools");
    }

    /// The row must not offer a version this engine will refuse on install.
    #[test]
    fn the_offered_version_is_the_newest_this_engine_can_run() {
        let idx = Index::parse(SAMPLE).unwrap();
        let grass = idx.find("com.example.grass").unwrap();
        assert_eq!(grass.newest().unwrap().version, Version::new(2, 0, 0));
        let best = grass.best_for(&Version::new(0, 55, 0)).unwrap();
        assert_eq!(best.version, Version::new(1, 4, 0));
        assert_eq!(best.rev.as_deref(), Some("v1.4.0"));
    }

    #[test]
    fn a_release_with_no_engine_range_runs_anywhere() {
        let idx = Index::parse(SAMPLE).unwrap();
        let audio = idx.find("com.other.audio").unwrap();
        assert!(audio.best_for(&Version::new(0, 1, 0)).is_some());
    }

    #[test]
    fn search_needs_every_word_to_match() {
        let idx = Index::parse(SAMPLE).unwrap();
        assert_eq!(idx.search("grass").len(), 1);
        assert_eq!(idx.search("grass terrain").len(), 1);
        assert_eq!(idx.search("grass reverb").len(), 0);
        assert_eq!(idx.search("").len(), 2);
        // Keywords count, and so does the id.
        assert_eq!(idx.search("vegetation").len(), 1);
        assert_eq!(idx.search("com.other").len(), 1);
    }

    #[test]
    fn a_name_that_starts_with_the_query_sorts_first() {
        let idx = Index::parse(
            r#"{"packages":[
                {"id":"com.a.b","name":"Zebra grass","versions":[]},
                {"id":"com.c.d","name":"Grass Tools","versions":[]}
            ]}"#,
        )
        .unwrap();
        let hits = idx.search("grass");
        assert_eq!(hits[0].name, "Grass Tools");
    }

    #[test]
    fn a_malformed_catalogue_says_so_in_words() {
        let err = Index::parse("{ nope").unwrap_err();
        assert!(err.contains("catalogue"), "{err}");
    }

    /// A package nobody has reviewed must not read as one everybody hated, so
    /// the absence of a rating is a different thing from a score of zero.
    #[test]
    fn an_unreviewed_package_has_no_rating_rather_than_a_zero() {
        let idx = Index::parse(SAMPLE).unwrap();
        assert!(idx.find("com.other.audio").unwrap().rating.is_none());

        let rated = Index::parse(
            r#"{"packages":[{"id":"a.b","name":"A","rating":{"score":4.3,"count":12},"versions":[]}]}"#,
        )
        .unwrap();
        let r = rated.find("a.b").unwrap().rating.unwrap();
        assert_eq!((r.score, r.count), (4.3, 12));
    }

    /// The field was added after the reader shipped. Every already-published
    /// catalogue must keep parsing, and a catalogue carrying it must not break
    /// an editor that predates it — which is the same property, tested from
    /// both ends.
    #[test]
    fn a_catalogue_without_ratings_still_parses_and_one_with_extra_fields_does_too() {
        assert!(Index::parse(SAMPLE).is_ok());
        let future = Index::parse(
            r#"{"packages":[{"id":"a.b","name":"A","versions":[],
                 "rating":{"score":5.0,"count":1},"somethingElse":{"x":1}}],"alsoNew":true}"#,
        )
        .unwrap();
        assert_eq!(future.packages.len(), 1);
    }

    #[test]
    fn reviews_read_and_average_what_is_actually_there() {
        let r = Reviews::parse(
            r#"{"id":"a.b","count":3,"reviews":[
                {"author":"X","rating":5,"body":"good","version":"1.0.0","date":"2026-08-12"},
                {"author":"Y","rating":4,"body":"","version":"1.1.0","date":"2026-08-12"},
                {"author":"Z","rating":3,"body":"meh","version":"1.1.0","date":"2026-08-13","edited":true}
            ]}"#,
        )
        .unwrap();
        assert_eq!(r.reviews.len(), 3);
        assert_eq!(r.mean(), Some(4.0));
        // An empty body is a real review, not a malformed one.
        assert_eq!(r.reviews[1].body, "");
        assert!(r.reviews[2].edited);
        // Nothing to average is None, not 0.0.
        assert_eq!(Reviews::default().mean(), None);
    }

    /// Reviews follow whichever catalogue is in use, so a studio on its own
    /// registry does not read fopull.com's reviews of a package it has never
    /// heard of.
    #[test]
    fn reviews_live_beside_the_catalogue_they_belong_to() {
        assert_eq!(
            reviews_url_for(DEFAULT_INDEX_URL, "com.example.grass"),
            "https://fopull.com/packages/reviews/com.example.grass.json"
        );
        assert_eq!(
            reviews_url_for("https://studio.internal/floptle/catalogue.json", "a.b"),
            "https://studio.internal/floptle/reviews/a.b.json"
        );
    }

    #[test]
    fn round_trips() {
        let idx = Index::parse(SAMPLE).unwrap();
        let text = serde_json::to_string(&idx).unwrap();
        assert_eq!(Index::parse(&text).unwrap(), idx);
    }
}
